[mypy]
python_version = 3.12
mypy_path = src
files = main.py, scripts, src, tests
explicit_package_bases = True
exclude = (?x)(
    ^venv/
    | ^src/control/tauri-react/node_modules/
    | ^src/control/tauri-react/src-tauri/target/
    )
strict = True
pretty = True
show_error_codes = True
show_error_context = True
warn_unreachable = True
